### ISSUE TITLE
Setting Meter size

### ISSUE THREAD

**Issue by MeestorX** [thedist/companion-module-utils#1]
The example callback looks like this:
```
callback: (feedback) => {
				const meter = presets.meter1({
				width: feedback.image.width,
				height: feedback.image.height,
				meter1: 50, // test value
				})
	
				return {
					imageBuffer: meter
				}
			}
```
Which works fine.
However, if I set width or height to any value other than `feedback.image.width` or the equivalent number, the meter does not appear. e.g. if I enter `height: feedback.image.height / 2` for a 1/2 size or `height: 20` for a short meter, the meter does not appear.

**Comment by thedist** [comment]
That's because Companion requires the imageBuffer match the resolution of the button it's being displayed on to, so the width/height is for if the resolution of the StreamDeck buttons changes, or if Companion supports other displays, in the future.

If you wish to display smaller bars, rather than using a preset which is specifically designed to be a bar of that size, you should instead use one of the base shapes provided in the module, such as the `bar` graphic, and that lets you size/position/colour the bar however you like, with as many segments of different colours as you like. If you need multiple bars, such as for multi-channel audio, create multiple graphics and then use the `stackImage` function to combine them all into a single imageBuffer. That's exactly how the preset works, it just puts together some predefined base shapes.

The documentation can be found here: https://github.com/thedist/companion-module-utils/blob/main/docs/graphics.md

**Comment by MeestorX** [comment]
Ok, so why are there a width and height parameters at all for this preset?

**Comment by thedist** [comment]
As I've said, if the resolution of StreamDeck buttons changes, or Companion provides support for other displays, the width and height params will create an imageBuffer for that resolution. Also, the resolution will be different if the top bar is enabled vs if it's disabled (ie, 72x72 without top bar, 72x58 with).
