### ISSUE TITLE
Icon suggestion, bar suggestion

### ISSUE THREAD

**Issue by phuvf** [thedist/companion-module-utils#3]
Firstly, thanks for this great set of tools, and examples - really helpful!

A couple of suggestions for the next version:

- A combined play/pause icon
- A reverse-animated bar 

As an example for the reverse bar, I have a *time remaining* preset, which counts down to zero with a horizontal progress bar beneath it. To me, it seems more sensible for this to start as a full bar, then shrinks to the right - so the motion of the bar matches the forward motion of the playhead.

**Comment by thedist** [comment]
I can certainly add a play/pause icon to the list for the next update.

As for a reverse-animated bar, I could do add a preset to make this easier, but it's already possible in a couple different ways:
1. You could have the value always 100 and utilize the `colors` array in the bar graphic and dynamically adjust the bars, so for example have a 0 size black bar, and a 100 size green bar, and as some value changes increase the black bar and decrease the size of the green bar. this would give them impression that the green bar is shrinking on the right. A little more fancy way would be to add another color in between, that's just 2 or 4 size wide perhaps, that appears to move right as the size of the colors left/right of it change. A downside to this is that the left color of the bar would be visible and not transparent.
2. Another option, is to again have the value 100, use a single color that's the full width of the bar, and instead adjust the `barWidth` and `offsetX` so that to shrink the bar to the right you would decrease the `barWidth` and increase the `offsetX` by 1, until `barWidth` is 0. This will give the effect of a bar shrinking to the right, and the left side of the bar would see through to the button background.

**Comment by phuvf** [comment]
These suggestions work great - thanks for the help and the really useful module.

**Comment by thedist** [comment]
I just released 0.5.0, which now has a `playPauze` icon type, and for a bar there's now an option `reverse` boolean option which when set to true will cause vertical bars to progress from top to bottom, and horizontal bars from right to left.
